// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcoreTransformersApp.Models;

namespace aspnetcoreTransformersApp.Migrations
{
    [DbContext(typeof(TransformerDBContext))]
    [Migration("20190331005708_InitialDBschema")]
    partial class InitialDBschema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aspnetcoreTransformersApp.Models.Transformer", b =>
                {
                    b.Property<int>("TransformerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllegianceId");

                    b.Property<int>("Courage");

                    b.Property<int>("Endurance");

                    b.Property<int>("Firepower");

                    b.Property<int>("Intelligence");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Rank");

                    b.Property<int>("Skill");

                    b.Property<int>("Speed");

                    b.Property<int>("Strength");

                    b.HasKey("TransformerId");

                    b.ToTable("Transformers");
                });

            modelBuilder.Entity("aspnetcoreTransformersApp.Models.TransformerAllegiance", b =>
                {
                    b.Property<int>("TransformerAllegianceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllegianceName");

                    b.Property<int?>("TransformerId");

                    b.HasKey("TransformerAllegianceId");

                    b.HasIndex("TransformerId");

                    b.ToTable("TransformerAllegiances");
                });

            modelBuilder.Entity("aspnetcoreTransformersApp.Models.TransformerAllegiance", b =>
                {
                    b.HasOne("aspnetcoreTransformersApp.Models.Transformer", "Transformer")
                        .WithMany("Allegiance")
                        .HasForeignKey("TransformerId");
                });
#pragma warning restore 612, 618
        }
    }
}
